CREATE DATABASE RESERVATION

USE RESERVATION


CREATE TABLE USER1
(
ID Integer not null PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
EMAIL VARCHAR(20),
PASSWORD VARCHAR(256), 
UNIQUE (EMAIL)
);

CREATE TABLE FLIGHT
(
  ID Integer not null PRIMARY KEY,
  FLIGHT_NUMBER VARCHAR(20)  NOT NULL, 
  OPERATING_AIRLINES VARCHAR(20)  NOT NULL,
  DEPARTURE_CITY VARCHAR(20)  NOT NULL,
  ARRIVAL_CITY VARCHAR(20)  NOT NULL,
  DATE_OF_DEPARTURE DATE  NOT NULL,
  ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PASSENGER
(
  ID Integer not null PRIMARY KEY,
  FIRST_NAME       VARCHAR(256),
  LAST_NAME    VARCHAR(256),
  MIDDLE_NAME   VARCHAR(256),
  EMAIL VARCHAR(50),
  PHONE VARCHAR(10)
);

CREATE TABLE RESERVATION
(
  ID Integer not null PRIMARY KEY,
  --CHECKED_IN TINYINT(1),
  NUMBER_OF_BAGS INT,
  PASSENGER_ID INT,
  FLIGHT_ID INT,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE,
  FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID)
);

alter table RESERVATION add CHECKED_IN SMALLINT;

SELECT * FROM USER1;

SELECT * FROM PASSENGER; 

SELECT * FROM FLIGHT;

SELECT * FROM RESERVATION;



DROP TABLE USER
DROP TABLE RESERVATION
DROP TABLE PASSENGER
DROP TABLE FLIGHT

DROP DATABASE RESERVATION